name: Mirror to Bitbucket Repo

on: workflow_dispatch

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com/jinzhi0123/jinzhi0123.git"
          destination-repo: "git@gitee.com/jinzhi0123/jinzhi0123.git"